"""Procedural synthetic wafer-map generator.

Lets the whole pipeline (loaders, models, training, triage, UI) run end-to-end
with zero downloads. Maps mimic MixedWM38 encoding:
  0 = blank (off-wafer), 1 = good die, 2 = defective die.
Labels are multi-hot over the 8 base defect types, so mixed-type maps are
generated by combining single-type patterns - exactly the MixedWM38 structure.
"""
from __future__ import annotations

import numpy as np

BASE_CLASSES = ["Center", "Donut", "Edge-Loc", "Edge-Ring", "Loc", "Near-full", "Scratch", "Random"]


def _wafer_mask(size: int) -> np.ndarray:
    """Circular wafer boundary mask (True = on-wafer)."""
    yy, xx = np.mgrid[0:size, 0:size]
    cx = cy = (size - 1) / 2
    r = size / 2
    return ((xx - cx) ** 2 + (yy - cy) ** 2) <= r ** 2


def _apply_pattern(defect: np.ndarray, mask: np.ndarray, pattern: str, rng: np.random.Generator) -> None:
    """Set defect=True for dies matching the named pattern (in place)."""
    size = mask.shape[0]
    yy, xx = np.mgrid[0:size, 0:size]
    cx = cy = (size - 1) / 2
    dist = np.sqrt((xx - cx) ** 2 + (yy - cy) ** 2)
    rmax = size / 2

    if pattern == "Center":
        rad = rmax * rng.uniform(0.18, 0.32)
        defect[(dist <= rad) & mask] = True
    elif pattern == "Donut":
        r0 = rmax * rng.uniform(0.30, 0.40)
        r1 = rmax * rng.uniform(0.55, 0.70)
        defect[(dist >= r0) & (dist <= r1) & mask] = True
    elif pattern == "Edge-Ring":
        r0 = rmax * rng.uniform(0.80, 0.88)
        defect[(dist >= r0) & mask] = True
    elif pattern == "Edge-Loc":
        ang0 = rng.uniform(0, 2 * np.pi)
        span = rng.uniform(0.6, 1.4)
        theta = np.arctan2(yy - cy, xx - cx)
        dtheta = np.angle(np.exp(1j * (theta - ang0)))
        defect[(dist >= rmax * 0.78) & (np.abs(dtheta) <= span) & mask] = True
    elif pattern == "Loc":
        ang = rng.uniform(0, 2 * np.pi)
        rr = rmax * rng.uniform(0.3, 0.6)
        bx, by = cx + rr * np.cos(ang), cy + rr * np.sin(ang)
        blob = np.sqrt((xx - bx) ** 2 + (yy - by) ** 2) <= rmax * rng.uniform(0.12, 0.20)
        defect[blob & mask] = True
    elif pattern == "Near-full":
        p = rng.uniform(0.70, 0.92)
        defect[mask & (rng.random((size, size)) < p)] = True
    elif pattern == "Scratch":
        ang = rng.uniform(0, np.pi)
        # distance from a line through center at angle `ang`
        line = np.abs((xx - cx) * np.sin(ang) - (yy - cy) * np.cos(ang))
        width = rng.uniform(0.6, 1.4)
        defect[(line <= width) & mask] = True
    elif pattern == "Random":
        p = rng.uniform(0.06, 0.14)
        defect[mask & (rng.random((size, size)) < p)] = True


def generate(n: int, size: int = 52, seed: int = 42,
             mixed_fraction: float = 0.45, none_fraction: float = 0.10):
    """Generate (X, Y): X is (n, size, size) uint8 in {0,1,2}, Y is (n, 8) float multi-hot.

    A fraction of maps are 'none' (no defect), some single-type, some mixed-type.
    """
    rng = np.random.default_rng(seed)
    mask = _wafer_mask(size)
    n_classes = len(BASE_CLASSES)
    X = np.zeros((n, size, size), dtype=np.uint8)
    Y = np.zeros((n, n_classes), dtype=np.float32)

    for i in range(n):
        wmap = np.where(mask, 1, 0).astype(np.uint8)   # 1 = good die
        defect = np.zeros((size, size), dtype=bool)
        u = rng.random()
        if u < none_fraction:
            chosen: list[int] = []                       # none
        elif u < none_fraction + (1 - none_fraction) * (1 - mixed_fraction):
            chosen = [int(rng.integers(0, n_classes))]   # single
        else:
            k = int(rng.integers(2, 4))                  # 2-3 mixed
            chosen = list(rng.choice(n_classes, size=k, replace=False))
        for c in chosen:
            _apply_pattern(defect, mask, BASE_CLASSES[c], rng)
            Y[i, c] = 1.0
        wmap[defect & mask] = 2                          # 2 = defective die
        X[i] = wmap
    return X, Y


def save_npz(path, n: int = 2000, size: int = 52, seed: int = 42) -> None:
    """Generate and save a synthetic dataset in MixedWM38-compatible .npz layout."""
    from pathlib import Path as _P
    X, Y = generate(n=n, size=size, seed=seed)
    _P(path).parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(path, arr_0=X, arr_1=Y)
